# Generated by Django 3.2.7 on 2021-09-19 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DiaSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diaSemana', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='telefono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numTelefono', models.IntegerField(default=0)),
                ('numWhatsapp', models.IntegerField(default=0)),
                ('numTelefonoFijo', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoCategoria', models.CharField(max_length=20)),
                ('valorCategoria', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='tipoCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoProcedimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Citas.especialidades')),
            ],
        ),
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=40)),
                ('apellidos', models.CharField(max_length=40)),
                ('identificacion', models.IntegerField(default=0)),
                ('direccion', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('edad', models.IntegerField(default=1)),
                ('telefono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Citas.telefono')),
                ('tipoUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Citas.tipocategoria')),
            ],
        ),
        migrations.CreateModel(
            name='Medicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcionPersonal', models.TextField(blank=True, max_length=500, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='')),
                ('nombres', models.CharField(max_length=40)),
                ('apellidos', models.CharField(max_length=40)),
                ('identificacion', models.IntegerField(default=0)),
                ('numTarjetaProfesional', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('edad', models.IntegerField(blank=True, default=1, null=True)),
                ('horariosDisponibles', models.DateTimeField(auto_now_add=True)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Citas.especialidades')),
                ('telefono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Citas.telefono')),
            ],
        ),
        migrations.CreateModel(
            name='LugarCitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=50)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Citas.ciudades')),
            ],
        ),
        migrations.CreateModel(
            name='HorasCitasDiarias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaDia', models.TimeField()),
                ('diaSemana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Citas.diasemana')),
                ('nombreMedico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Citas.medicos')),
            ],
        ),
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaServicio', models.TimeField()),
                ('horaCita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Citas.horascitasdiarias')),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Citas.lugarcitas')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Citas.medicos')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Citas.pacientes')),
                ('tipoServicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Citas.tipoprocedimiento')),
                ('tipocita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Citas.tipocita')),
            ],
        ),
    ]
