# Generated by Django 3.2.7 on 2021-09-29 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Medicos', '0001_initial'),
        ('TipoCitas', '0001_initial'),
        ('Pacientes', '0001_initial'),
        ('LugarCitas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaCita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medicos.horascitasdiarias')),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LugarCitas.lugarcita')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medicos.medicos')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pacientes.pacientes')),
                ('tipoCita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TipoCitas.tipocita')),
                ('tipoServicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LugarCitas.tipoprocedimiento')),
            ],
        ),
    ]
