# Generated by Django 3.2.7 on 2021-09-19 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicos',
            name='telefono',
            field=models.CharField(max_length=50),
        ),
    ]
